apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    deployOVS: 'false'
  resourceVersion: '116992'
  name: kubevirt-hyperconverged
  uid: c1d06ba5-86ac-4900-995c-76419267a7f8
  creationTimestamp: '2024-11-23T19:35:54Z'
  generation: 2
  namespace: openshift-cnv
  finalizers:
    - kubevirt.io/hyperconverged
  labels:
    app: kubevirt-hyperconverged
spec:
  virtualMachineOptions:
    disableFreePageReporting: false
    disableSerialConsoleLog: true
  higherWorkloadDensity:
    memoryOvercommitPercentage: 100
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  infra: {}
  applicationAwareConfig:
    allowApplicationAwareClusterResourceQuota: false
    vmiCalcConfigName: DedicatedVirtualResources
  evictionStrategy: LiveMigrate
  featureGates:
    deployTektonTaskResources: false
    enableCommonBootImageImport: true
    withHostPassthroughCPU: false
    downwardMetrics: false
    disableMDevConfiguration: false
    enableApplicationAwareQuota: false
    deployKubeSecondaryDNS: false
    nonRoot: true
    alignCPUs: false
    enableManagedTenantQuota: false
    primaryUserDefinedNetworkBinding: false
    deployVmConsoleProxy: false
    persistentReservation: false
    autoResourceLimits: false
    deployKubevirtIpamController: false
  workloadUpdateStrategy:
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
      - LiveMigrate
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  workloads: {}
  resourceRequirements:
    vmiCPUAllocationRatio: 10
